### ISSUE TITLE
VPN was looking the location and the error appears

### ISSUE THREAD

**Issue by Ilyaviznitsa** [AdguardTeam/AdGuardVPNExtension#173] opened 2024-05-03 09:32 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.17

### Environment

```markdown
- OS: Microsoft Windows 10
- Browser: Yandex Browser
```

### Issue Details

A VPN was searching the locations and the error appears

### Actual Behavior

I was logged on to my account, and he is loading, error, i clicked on try again and he is searching a locations, and there was an error again! And it's on a loop

### Expected Behavior

I expected that was not that happened

### Screenshots

Loading
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/117360468/a3aa9944-6329-4c44-8565-45567d92ac07)
Error
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/117360468/aa1dbdaa-0a57-49a2-a5f7-c24be5029901)
Searching Locations
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/117360468/73c13450-ba62-431b-8d1f-c55cb0447dee)

**Comment by alexx7311** [comment] 2024-05-03 09:43
@Ilyaviznitsa Hello! Would you mind sharing what country you are in?

**Comment by Ilyaviznitsa** [comment] 2024-05-04 04:42
Russia 🇷🇺

**Comment by alexx7311** [comment] 2024-05-06 08:35
@Ilyaviznitsa Please use [desktop version of AdGuard](https://adguardvpn-help.com/en/welcome.html). The extension will work unstably in Russia.
Closing as a duplicate of https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148

**Closed** 2024-05-06 08:36 UTC
Labels: Priority: P4
